import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL("https://sellluxurywatch.my/"), // Base URL for resolving relative URLs
  alternates: {
    canonical: "/",
  },
};

export const metadata: ExtendedMetadata = {
  title: "Sell Rolex Watch | High Price Purchase | in Malaysia",
  description:
    "Please visit us to sell your Rolex at a good price! We accept any Rolex models like Datejust, Submariner and Explorer.",
  keywords: "luxury, watch, sell, branded, high price",
  ogTitle: "Sell Rolex Watch | High Price Purchase | in Malaysia",
  ogDescription:
    "Please visit us to sell your Rolex at a good price! We accept any Rolex models like Datejust, Submariner and Explorer.",
  ogImage: "/images/jc-logo.png",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="relative overflow-hidden">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
